### ISSUE TITLE
État des tests unitaires

### ISSUE THREAD

**Issue by azmeuk** [EsupPortail/Esup-Pod#1057]
Bonjour à tous,

En travaillant sur l'implémentation d'activitypub, nous avons commencé à écrire des tests unitaires. Si on arrive à lancer nos tests de manière isolée, on se rend compte que la suite de tests échoue, sur la branche develop par exemple.

En regardant de plus près, [les tests dans github actions](
https://github.com/EsupPortail/Esup-Pod/actions/runs/7801404671/job/21276412686#step:11:767) semblent aussi échouer, bien qu'ils soient affichés en vert.

```
python manage.py test --settings=pod.main.test_settings
Creating test database for alias 'default'...
pre_migrate - Start save_previous_data
pre_migrate - save_previous_data --> OK
Start save_previous_data | playlists
no such table: playlist_playlist
no such table: playlist_playlistelement
no such table: favorite_favorite
save_previous_data --> OK | playlists
---> Creating missing configurations...
--> maintenance_mode
-> Creating...
--> maintenance_text_short
-> Creating...
--> maintenance_text_welcome
-> Creating...
--> maintenance_text_disabled
-> Creating...
--> maintenance_sheduled
-> Creating...
--> maintenance_text_sheduled
-> Creating...
---> Creating missing flat pages and links...
--> Search missing flat pages and footer links...
-> New page created at “/”.
-> New page created at “/legal_notice/”.
-> New page created at “/accessibility/”.
-> New Footer link created for “Legal Notice”.
-> New Footer link created for “Accessibility: Partially compliant”.
Start set_default_site
set_default_site --> OK
post_migrate - Start send_previous_data
Start fix_transcript
fix_transcript --> OK
Start send_previous_data | playlists
Start create_new_favorites
create_new_favorites --> OK
send_previous_data --> OK | playlists
Remove previous table : favorite_favorite --> OK
Traceback (most recent call last):
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: video_usermarkertime

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/ssd/dev/yaal/Esup-Pod/manage.py", line 39, in <module>
    execute_from_command_line(sys.argv)
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/core/management/commands/test.py", line 55, in handle
    failures = test_runner.run_tests(test_labels)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/test/runner.py", line 725, in run_tests
    old_config = self.setup_databases(aliases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/test/runner.py", line 643, in setup_databases
    return _setup_databases(
           ^^^^^^^^^^^^^^^^^
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/test/utils.py", line 179, in setup_databases
    connection.creation.create_test_db(
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/db/backends/base/creation.py", line 90, in create_test_db
    self.connection._test_serialized_contents = self.serialize_db_to_string()
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/db/backends/base/creation.py", line 136, in serialize_db_to_string
    serializers.serialize("json", get_objects(), indent=None, stream=out)
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/core/serializers/__init__.py", line 129, in serialize
    s.serialize(queryset, **options)
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/core/serializers/base.py", line 90, in serialize
    for count, obj in enumerate(queryset, start=1):
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/db/backends/base/creation.py", line 133, in get_objects
    yield from queryset.iterator()
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/db/models/query.py", line 353, in _iterator
    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/.virtualenvs/Esup-Pod-naas/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: video_usermarkertime
```

**Comment by ptitloup** [comment]
Les tests passent maintenant. Tenez nous au courant si cela continue

**Comment by azmeuk** [comment]
Merci !
