### ISSUE TITLE
debian 10 buster installation : backtrace urllib3 create_pod_index

### ISSUE THREAD

**Issue by guerby** [EsupPortail/Esup-Pod#315]
En suivant les instructions https://www.esup-portail.org/wiki/display/ES/installation mais sur une debian 10 (au lieu de 9.4)

La version d'elasticsearch est 7.x au lieu de 6.x, a noter cluster_uuid = "_na_" ?

```
jango_pod) pod@pod:~/django_projects/podv2$ curl -XGET "127.0.0.1:9200"
{
  "name" : "pod-1",
  "cluster_name" : "pod-application",
  "cluster_uuid" : "_na_",
  "version" : {
    "number" : "7.8.1",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "b5ca9c58fb664ca8bf9e4057fc229b3396bf3a89",
    "build_date" : "2020-07-21T16:40:44.668009Z",
    "build_snapshot" : false,
    "lucene_version" : "8.5.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

Et la création de l'index échoue avec des backtraces apres le dependencywarning sur urllib3 :

```
(django_pod) pod@pod:~/django_projects/podv2$ python manage.py create_pod_index
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.9) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
DELETE http://127.0.0.1:9200/pod [status:N/A request:10.009s]
Traceback (most recent call last):
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=9200): Read timed out. (read timeout=10)
Traceback (most recent call last):
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=9200): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/django_projects/podv2/pod/video_search/utils.py", line 69, in delete_index_es
    delete = es.indices.delete(index=ES_INDEX)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/elasticsearch/client/indices.py", line 185, in delete
    params=params)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 180, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='127.0.0.1', port=9200): Read timed out. (read timeout=10))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/django_projects/podv2/pod/video_search/management/commands/create_pod_index.py", line 17, in handle
    delete_index_es()
  File "/usr/local/django_projects/podv2/pod/video_search/utils.py", line 75, in delete_index_es
    (e.status_code, e.error, e.info['error']['reason']))
TypeError: 'ReadTimeoutError' object is not subscriptable
```

**Comment by guerby** [comment]
j'ai commente le delete dans ./pod/video_search/management/commands/create_pod_index.py

```
    def handle(self, *args, **options):
        #delete_index_es()
        ....
```

Et modulo le warning ça a l'air de marcher :

```
(django_pod) pod@pod:~/django_projects/podv2$ python manage.py create_pod_index
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.9) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
PUT http://127.0.0.1:9200/pod [status:400 request:0.021s]
Pod index already exists: parse_exception
Successfully create index Video
(django_pod) pod@pod:~/django_projects/podv2$ 
```

**Comment by guerby** [comment]
Je pense avoir trouvé, il faut dans /etc/elasticsearch/elasticsearch.yml definir 

```
cluster.initial_master_nodes: ["pod-1"]
```

Puis `systemctl restart elasticsearch` et ensuite le curl a bien un cluster_uuid :+1: 

```
$ curl -XGET "127.0.0.1:9200"
{
  "name" : "pod-1",
  "cluster_name" : "pod-application",
  "cluster_uuid" : "ooJ9azgQQyCuA1hr0UxxbQ",
  "version" : {
    "number" : "7.8.1",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "b5ca9c58fb664ca8bf9e4057fc229b3396bf3a89",
    "build_date" : "2020-07-21T16:40:44.668009Z",
    "build_snapshot" : false,
    "lucene_version" : "8.5.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by ptitloup** [comment]
Nous n'avons pas pu mettre à jour ES vers la 7 pour le moment. Nous ne pouvons que conseiller de rester en v6.
