### ISSUE TITLE
probleme encodage déporté avec module mysqlclient en 2.1

### ISSUE THREAD

**Issue by fanfounet** [EsupPortail/Esup-Pod#598]
le client mysqlclient 2.1 provoque une erreur lors de l'encodage 
`ERROR/ForkPoolWorker-8] Task pod.main.tasks.task_start_encode[0e26cd71-3a5f-4269-838f-6bcf3c201689] raised unexpected: KeyError(<class 'bytes'>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/django_projects/podv2/pod/main/tasks.py", line 9, in task_start_encode
    encode_video(video_id)
  File "/usr/local/django_projects/podv2/pod/video/encode.py", line 228, in encode_video
    video_to_encode = Video.objects.get(id=video_id)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 887, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn.encoders[SafeBytes] = conn.encoders[bytes]
KeyError: <class 'bytes'>`

Problème résolu en passant en 2.0.3
`pip3 install mysqlclient==2.0.3`

**Comment by ptitloup** [comment]
> Problème résolu en passant en 2.0.3
> pip3 install mysqlclient==2.0.3
